riptide_rviz::OverlayDisplay
OverlayObject::SharedPtr riptide_rviz::OverlayDisplay::overlay_
Referenced by onDisable, onEnable, onInitialize, reset, update.
int riptide_rviz::OverlayDisplay::texture_width_
Referenced by OverlayDisplay, update, updateWidth.
int riptide_rviz::OverlayDisplay::texture_height_
Referenced by OverlayDisplay, update, updateHeight.
int riptide_rviz::OverlayDisplay::horizontal_dist_
Referenced by update, updateHorizontalDistance.
int riptide_rviz::OverlayDisplay::vertical_dist_
Referenced by update, updateVerticalDistance.
HorizontalAlignment riptide_rviz::OverlayDisplay::horizontal_alignment_
Referenced by update, updateHorizontalAlignment.
VerticalAlignment riptide_rviz::OverlayDisplay::vertical_alignment_
Referenced by update, updateVerticalAlignment.
QColor riptide_rviz::OverlayDisplay::bg_color_
Referenced by OverlayDisplay, update.
bool riptide_rviz::OverlayDisplay::require_update_texture_
Referenced by addArc, addCircle, addText, clearElements, onInitialize, OverlayDisplay, update, updateArc, updateCircle, riptide_rviz::DiagnosticOverlay::updateFont, updateHeight, updateHorizontalAlignment, updateHorizontalDistance, updateText, updateVerticalAlignment, updateVerticalDistance, updateWidth.
rviz_common::properties::IntProperty* riptide_rviz::OverlayDisplay::hor_dist_property_
Referenced by OverlayDisplay, updateHorizontalDistance.
rviz_common::properties::IntProperty* riptide_rviz::OverlayDisplay::ver_dist_property_
Referenced by OverlayDisplay, updateVerticalDistance.
rviz_common::properties::EnumProperty* riptide_rviz::OverlayDisplay::hor_alignment_property_
Referenced by OverlayDisplay, updateHorizontalAlignment.
rviz_common::properties::EnumProperty* riptide_rviz::OverlayDisplay::ver_alignment_property_
Referenced by OverlayDisplay, updateVerticalAlignment.
rviz_common::properties::IntProperty* riptide_rviz::OverlayDisplay::width_property_
Referenced by OverlayDisplay, updateWidth.
rviz_common::properties::IntProperty* riptide_rviz::OverlayDisplay::height_property_
Referenced by OverlayDisplay, updateHeight.
std::vector<PaintedTextConfig> riptide_rviz::OverlayDisplay::text_vector_
Referenced by addText, clearElements, update, updateText.
std::vector<PaintedCircleConfig> riptide_rviz::OverlayDisplay::circle_vector_
Referenced by addCircle, clearElements, update, updateCircle.
std::vector<PaintedArcConfig> riptide_rviz::OverlayDisplay::arc_vector_
Referenced by addArc, clearElements, update, updateArc.
riptide_rviz::OverlayDisplay::OverlayDisplay()
References bg_color_, riptide_rviz::BOTTOM, riptide_rviz::CENTER, height_property_, hor_alignment_property_, hor_dist_property_, riptide_rviz::LEFT, require_update_texture_, riptide_rviz::RIGHT, texture_height_, texture_width_, riptide_rviz::TOP, updateHeight, updateHorizontalAlignment, updateHorizontalDistance, updateVerticalAlignment, updateVerticalDistance, updateWidth, ver_alignment_property_, ver_dist_property_, width_property_.
riptide_rviz::OverlayDisplay::~OverlayDisplay()
References onDisable.
void riptide_rviz::OverlayDisplay::onInitialize() override
References onEnable, overlay_, require_update_texture_, updateHeight, updateHorizontalAlignment, updateHorizontalDistance, updateVerticalAlignment, updateVerticalDistance, updateWidth.
Referenced by riptide_rviz::DiagnosticOverlay::onInitialize.
void riptide_rviz::OverlayDisplay::onEnable() override
References overlay_.
Referenced by riptide_rviz::DiagnosticOverlay::onEnable, onInitialize.
void riptide_rviz::OverlayDisplay::onDisable() override
References overlay_.
Referenced by riptide_rviz::DiagnosticOverlay::onDisable, ~OverlayDisplay.
void riptide_rviz::OverlayDisplay::update(float wall_dt, float ros_dt) override
References arc_vector_, bg_color_, circle_vector_, riptide_rviz::ScopedPixelBuffer::getQImage, horizontal_alignment_, horizontal_dist_, overlay_, paintArc, paintCircle, paintText, require_update_texture_, text_vector_, texture_height_, texture_width_, vertical_alignment_, vertical_dist_.
Referenced by riptide_rviz::DiagnosticOverlay::update.
void riptide_rviz::OverlayDisplay::reset() override
References overlay_.
Referenced by riptide_rviz::DiagnosticOverlay::reset.
int riptide_rviz::OverlayDisplay::addText(const PaintedTextConfig &config)
References require_update_texture_, text_vector_.
Referenced by riptide_rviz::DiagnosticOverlay::onInitialize.
int riptide_rviz::OverlayDisplay::addCircle(const PaintedCircleConfig &config)
References circle_vector_, require_update_texture_.
Referenced by riptide_rviz::DiagnosticOverlay::onInitialize.
int riptide_rviz::OverlayDisplay::addArc(const PaintedArcConfig &config)
References arc_vector_, require_update_texture_.
Referenced by riptide_rviz::DiagnosticOverlay::onInitialize.
void riptide_rviz::OverlayDisplay::updateText(int index, const PaintedTextConfig &config)
References require_update_texture_, text_vector_.
Referenced by riptide_rviz::DiagnosticOverlay::batteryCallback, riptide_rviz::DiagnosticOverlay::checkTimeout, riptide_rviz::DiagnosticOverlay::diagnosticCallback, riptide_rviz::DiagnosticOverlay::gyroCallback.
void riptide_rviz::OverlayDisplay::updateCircle(int index, const PaintedCircleConfig &config)
References circle_vector_, require_update_texture_.
Referenced by riptide_rviz::DiagnosticOverlay::checkTimeout, riptide_rviz::DiagnosticOverlay::dfcCallback, riptide_rviz::DiagnosticOverlay::diagnosticCallback, riptide_rviz::DiagnosticOverlay::killCallback, riptide_rviz::DiagnosticOverlay::leakCallback, riptide_rviz::DiagnosticOverlay::pressureCallback, riptide_rviz::DiagnosticOverlay::zedCallback.
void riptide_rviz::OverlayDisplay::updateArc(int id, const PaintedArcConfig &config)
References arc_vector_, require_update_texture_.
Referenced by riptide_rviz::DiagnosticOverlay::checkTimeout, riptide_rviz::DiagnosticOverlay::diagnosticCallback, riptide_rviz::DiagnosticOverlay::gyroCallback.
void riptide_rviz::OverlayDisplay::clearElements()
References arc_vector_, circle_vector_, require_update_texture_, text_vector_.
void riptide_rviz::OverlayDisplay::paintText(const PaintedTextConfig &config, QPainter &painter)
Helper method for rendering text onto a QImage with a QPainter config a painted text config containing the location to paint the font and size to use, the text to put in and the overall width and height of the panel painter the painter to use while building the text overlay. Passed by refrence to keep the changes pointed at the correct image
References riptide_rviz::PaintedTextConfig::font_name_, riptide_rviz::PaintedTextConfig::font_size_, riptide_rviz::PaintedTextConfig::height_, riptide_rviz::PaintedTextConfig::invert_shadow_, riptide_rviz::PaintedTextConfig::line_width_, riptide_rviz::PaintedTextConfig::text_, riptide_rviz::PaintedTextConfig::text_color_, riptide_rviz::PaintedTextConfig::width_, riptide_rviz::PaintedTextConfig::x_, riptide_rviz::PaintedTextConfig::y_.
Referenced by update.
void riptide_rviz::OverlayDisplay::paintCircle(const PaintedCircleConfig &config, QPainter &painter)
References riptide_rviz::PaintedCircleConfig::inner_color_, riptide_rviz::PaintedCircleConfig::inner_radius_, riptide_rviz::PaintedCircleConfig::outer_color_, riptide_rviz::PaintedCircleConfig::outer_radius_, riptide_rviz::PaintedCircleConfig::x_, riptide_rviz::PaintedCircleConfig::y_.
Referenced by update.
void riptide_rviz::OverlayDisplay::paintArc(const PaintedArcConfig &config, QPainter &painter)
References riptide_rviz::PaintedArcConfig::end_angle_, riptide_rviz::PaintedArcConfig::line_color_, riptide_rviz::PaintedArcConfig::line_width_, riptide_rviz::PaintedArcConfig::radius_, riptide_rviz::PaintedArcConfig::start_angle_, riptide_rviz::PaintedArcConfig::x_, riptide_rviz::PaintedArcConfig::y_.
Referenced by update.
void riptide_rviz::OverlayDisplay::updateHorizontalDistance()
References hor_dist_property_, horizontal_dist_, require_update_texture_.
Referenced by onInitialize, OverlayDisplay.
void riptide_rviz::OverlayDisplay::updateVerticalDistance()
References require_update_texture_, ver_dist_property_, vertical_dist_.
Referenced by onInitialize, OverlayDisplay.
void riptide_rviz::OverlayDisplay::updateHorizontalAlignment()
References hor_alignment_property_, horizontal_alignment_, require_update_texture_.
Referenced by onInitialize, OverlayDisplay.
void riptide_rviz::OverlayDisplay::updateVerticalAlignment()
References require_update_texture_, ver_alignment_property_, vertical_alignment_.
Referenced by onInitialize, OverlayDisplay.
void riptide_rviz::OverlayDisplay::updateWidth()
References require_update_texture_, texture_width_, width_property_.
Referenced by onInitialize, OverlayDisplay.
void riptide_rviz::OverlayDisplay::updateHeight()
References height_property_, require_update_texture_, texture_height_.
Referenced by onInitialize, OverlayDisplay.