riptide_rviz::Bag
std::vector<std::shared_ptr<RecipeBag> > riptide_rviz::Bag::bags
Referenced by getAllBags, loadXml.
RecipeXMLError riptide_rviz::Bag::loadXml(std::string const &recipePath)
References bags, riptide_rviz::EMPTY_BAGS, riptide_rviz::RecipeXMLError::errorCode, loadXml, riptide_rviz::NO_BAGS_TAG, riptide_rviz::NON_BAG_TAG, parseBagTag, riptide_rviz::SUCCESS.
Referenced by loadXml.
std::vector< std::shared_ptr< RecipeBag > > riptide_rviz::Bag::getAllBags()
References bags, getAllBags.
Referenced by getAllBags.
bool riptide_rviz::Bag::operator==(const Bag &)
bool riptide_rviz::Bag::operator!=(const Bag &)
References parseBagTag.
RecipeXMLError riptide_rviz::Bag::parseBagTag(const tinyxml2::XMLElement *bagXML, RecipeBag &launch)
References riptide_rviz::MISSING_NAME_ATTRIBUTE, riptide_rviz::RecipeBag::name, parseBagTag, riptide_rviz::RecipeTopicData::parseXml, riptide_rviz::SUCCESS, riptide_rviz::RecipeBag::topicList, riptide_rviz::UNKNOWN_TAG_TYPE.
Referenced by loadXml, operator!=, parseBagTag.