riptide_rviz::OverlayObject
using riptide_rviz::OverlayObject::SharedPtr = std::shared_ptr<OverlayObject>
const std::string riptide_rviz::OverlayObject::name_
Referenced by getName, OverlayObject, updateTextureSize.
Ogre::Overlay* riptide_rviz::OverlayObject::overlay_
Referenced by hide, isVisible, OverlayObject, show, ~OverlayObject.
Ogre::PanelOverlayElement* riptide_rviz::OverlayObject::panel_
Referenced by OverlayObject, setDimensions, setPosition, ~OverlayObject.
Ogre::MaterialPtr riptide_rviz::OverlayObject::panel_material_
Referenced by OverlayObject, updateTextureSize, ~OverlayObject.
Ogre::TexturePtr riptide_rviz::OverlayObject::texture_
Referenced by getBuffer, getTextureHeight, getTextureWidth, isTextureReady, updateTextureSize.
riptide_rviz::OverlayObject::OverlayObject(const std::string &name)
References name_, overlay_, panel_, panel_material_.
riptide_rviz::OverlayObject::~OverlayObject()
References overlay_, panel_, panel_material_.
std::string riptide_rviz::OverlayObject::getName() const
References name_.
void riptide_rviz::OverlayObject::hide()
References overlay_.
void riptide_rviz::OverlayObject::show()
References overlay_.
bool riptide_rviz::OverlayObject::isTextureReady() const
References texture_.
Referenced by getBuffer, getTextureHeight, getTextureWidth, updateTextureSize.
void riptide_rviz::OverlayObject::updateTextureSize(unsigned int width, unsigned int height)
References isTextureReady, name_, panel_material_, texture_.
ScopedPixelBuffer riptide_rviz::OverlayObject::getBuffer()
References isTextureReady, texture_.
void riptide_rviz::OverlayObject::setPosition(double hor_dist, double ver_dist, HorizontalAlignment hor_alignment=HorizontalAlignment::LEFT, VerticalAlignment ver_alignment=VerticalAlignment::TOP)
References riptide_rviz::BOTTOM, riptide_rviz::CENTER, riptide_rviz::LEFT, panel_, riptide_rviz::RIGHT, riptide_rviz::TOP.
void riptide_rviz::OverlayObject::setDimensions(double width, double height)
References panel_.
bool riptide_rviz::OverlayObject::isVisible() const
References overlay_.
unsigned int riptide_rviz::OverlayObject::getTextureWidth() const
References isTextureReady, texture_.
Referenced by riptide_rviz::ScopedPixelBuffer::getQImage, riptide_rviz::ScopedPixelBuffer::getQImage.
unsigned int riptide_rviz::OverlayObject::getTextureHeight() const
References isTextureReady, texture_.
Referenced by riptide_rviz::ScopedPixelBuffer::getQImage, riptide_rviz::ScopedPixelBuffer::getQImage.