riptide_rviz::ControlPanel
control_modes
using riptide_rviz::ControlPanel::Trigger = std_srvs::srv::Trigger
using riptide_rviz::ControlPanel::SetBool = std_srvs::srv::SetBool
using riptide_rviz::ControlPanel::SetPose = robot_localization::srv::SetPose
using riptide_rviz::ControlPanel::CalibrateDrag = riptide_msgs2::action::CalibrateDragNew
using riptide_rviz::ControlPanel::CalibrateDragGH = rclcpp_action::ClientGoalHandle<CalibrateDrag>
bool riptide_rviz::ControlPanel::last_duplicate_state
Referenced by load, refreshUI.
std::map<std::string, bool> riptide_rviz::ControlPanel::topic_duplicate_status
Referenced by checkForDuplicateTopics.
std::string riptide_rviz::ControlPanel::duplicate_topics_list
Referenced by checkForDuplicateTopics, refreshUI.
Ui_ControlPanel* riptide_rviz::ControlPanel::uiPanel
Referenced by ControlPanel, diagCallback, event, getDesiredSetpointFromTextboxes, getSolenoidStatuses, handleCommand, handleCurrent, handleDisable, handleEnable, handleLocalDive, handleReloadController, handleStartDragCal, load, odomCallback, onInitialize, refreshUI, regHousingPressureCallback, regPressureCallback, selectedPose, sendKillMsgTimer, setDragCalRunning, setptMarkerFeedback, setSolenoidStatuses, simulator_apply_clickec, startBallastLogData, switchMode, syncSetptMarkerToTextboxes, tankPressureCallback, toggleDegrees, updateCalStatus, ~ControlPanel.
std::string riptide_rviz::ControlPanel::robot_ns
Referenced by load, save, switchMode.
std::string riptide_rviz::ControlPanel::hostname
Referenced by load, sendKillMsgTimer.
double riptide_rviz::ControlPanel::max_depth_in_place
Referenced by load, refreshUI, save.
double riptide_rviz::ControlPanel::tgt_in_place_depth
Referenced by load, save.
std::chrono::duration<double> riptide_rviz::ControlPanel::odom_timeout
Referenced by load, odomCallback, refreshUI, save.
uint8_t riptide_rviz::ControlPanel::ctrlMode
Referenced by ControlPanel, handleCommand, pubCurrentSetpoint, selectedPose, switchMode.
builtin_interfaces::msg::Time riptide_rviz::ControlPanel::odomTime
Referenced by odomCallback, refreshUI.
bool riptide_rviz::ControlPanel::vehicleEnabled
Referenced by handleDisable, handleEnable, refreshUI, sendKillMsgTimer, switchMode.
bool riptide_rviz::ControlPanel::degreeReadout
Referenced by handleCommand, odomCallback, selectedPose, setptMarkerFeedback, syncSetptMarkerToTextboxes, toggleDegrees.
bool riptide_rviz::ControlPanel::activeBallastEnabled
Referenced by load.
bool riptide_rviz::ControlPanel::ballastLogRunning
Referenced by exaustSolenoidCb, load, odomCallback, pressureSolenoidCb, refreshUI, regHousingPressureCallback, regPressureCallback, startBallastLogData, tankPressureCallback, waterSolenoidCb.
std::string riptide_rviz::ControlPanel::ballastLogFileName
Referenced by startBallastLogData, updateBallastLog.
rclcpp::Time riptide_rviz::ControlPanel::lastBallastLogTime
Referenced by load, updateBallastLog.
BallastLogData riptide_rviz::ControlPanel::ballastLogData
Referenced by exaustSolenoidCb, odomCallback, pressureSolenoidCb, regHousingPressureCallback, regPressureCallback, startBallastLogData, tankPressureCallback, updateBallastLog, waterSolenoidCb.
std::shared_ptr<QPixmap> riptide_rviz::ControlPanel::ballastDiagram
Referenced by event, onInitialize.
QTimer* riptide_rviz::ControlPanel::uiTimer
Referenced by load, ~ControlPanel.
pid_t riptide_rviz::ControlPanel::teleopPID
Referenced by ControlPanel, switchMode.
rclcpp::Publisher<riptide_msgs2::msg::ControllerCommand>::SharedPtr riptide_rviz::ControlPanel::ctrlCmdLinPub
Referenced by handleCommand, handleDisable, load.
rclcpp::Publisher<riptide_msgs2::msg::ControllerCommand>::SharedPtr riptide_rviz::ControlPanel::ctrlCmdAngPub
Referenced by handleCommand, handleDisable, load.
rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::auxPub
Referenced by handleAuxDown, handleAuxUp, load.
rclcpp::Publisher<riptide_msgs2::msg::KillSwitchReport>::SharedPtr riptide_rviz::ControlPanel::killStatePub
Referenced by load, sendKillMsgTimer.
rclcpp::Publisher<std_msgs::msg::Empty>::SharedPtr riptide_rviz::ControlPanel::dragCalTriggerPub
Referenced by handleTriggerDragCal, load.
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr riptide_rviz::ControlPanel::clawObjectPub
Referenced by load, simulator_apply_clickec.
rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::exaustSolenoidPub
Referenced by load, publishSolenoidStatuses.
rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::pressureSolenoidPub
Referenced by load, publishSolenoidStatuses.
rclcpp::Publisher<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::waterSolenoidPub
Referenced by load, publishSolenoidStatuses.
rclcpp::TimerBase::SharedPtr riptide_rviz::ControlPanel::killPubTimer
Referenced by load.
rclcpp::TimerBase::SharedPtr riptide_rviz::ControlPanel::setPointPubTimer
Referenced by load.
geometry_msgs::msg::Pose riptide_rviz::ControlPanel::lastCommandedPose
Referenced by handleCommand, load, pubCurrentSetpoint.
rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr riptide_rviz::ControlPanel::odomSub
Referenced by load.
rclcpp::Subscription<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr riptide_rviz::ControlPanel::diagSub
Referenced by load.
rclcpp::Subscription<geometry_msgs::msg::PoseStamped>::SharedPtr riptide_rviz::ControlPanel::selectPoseSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::exaustSolenoidSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::pressureSolenoidSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::ControlPanel::waterSolenoidSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr riptide_rviz::ControlPanel::regPressureSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr riptide_rviz::ControlPanel::regHousingPressureSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr riptide_rviz::ControlPanel::tankPressureSub
Referenced by load.
rclcpp::Client<Trigger>::SharedPtr riptide_rviz::ControlPanel::reloadCompleteClient
Referenced by handleReloadController, load.
rclcpp::Client<Trigger>::SharedPtr riptide_rviz::ControlPanel::reloadLiltankClient
Referenced by handleReloadController, load.
rclcpp::Client<SetBool>::SharedPtr riptide_rviz::ControlPanel::setTeleopClient
Referenced by load, switchMode.
rclcpp::Client<SetPose>::SharedPtr riptide_rviz::ControlPanel::setSimPoseClient
Referenced by load.
std::shared_future<Trigger::Response::SharedPtr> riptide_rviz::ControlPanel::activeClientFuture
Referenced by callTriggerService, waitForTriggerResponse.
std::shared_future<SetBool::Response::SharedPtr> riptide_rviz::ControlPanel::activeSetBoolClientFuture
Referenced by callSetBoolService, waitForSetBoolResponse.
std::shared_future<SetPose::Response::SharedPtr> riptide_rviz::ControlPanel::activeSetPoseClientFuture
Referenced by callSetPoseService, waitForSetPoseResponse.
int64_t riptide_rviz::ControlPanel::srvReqId
Referenced by callSetBoolService, callSetPoseService, callTriggerService, waitForSetBoolResponse, waitForSetPoseResponse, waitForTriggerResponse.
rclcpp::Time riptide_rviz::ControlPanel::clientSendTime
Referenced by callSetBoolService, callSetPoseService, callTriggerService, waitForSetBoolResponse, waitForSetPoseResponse, waitForTriggerResponse.
rclcpp_action::Client<CalibrateDrag>::SharedPtr riptide_rviz::ControlPanel::calibrateDrag
Referenced by handleStartDragCal, handleStopDragCal, load.
std::shared_ptr<interactive_markers::InteractiveMarkerServer> riptide_rviz::ControlPanel::setptServer
Referenced by load, switchMode, syncSetptMarkerToTextboxes.
visualization_msgs::msg::InteractiveMarker riptide_rviz::ControlPanel::interactiveSetpointMarker
Referenced by load, switchMode, syncSetptMarkerToTextboxes.
std::shared_ptr<tf2_ros::Buffer> riptide_rviz::ControlPanel::tf_buffer
Referenced by load, transformBetweenFrames.
std::shared_ptr<tf2_ros::TransformListener> riptide_rviz::ControlPanel::tf_listener
Referenced by load.
riptide_rviz::ControlPanel::ControlPanel(QWidget *parent=0)
References ctrlMode, DISABLED, teleopPID, uiPanel.
riptide_rviz::ControlPanel::~ControlPanel()
References uiPanel, uiTimer.
void riptide_rviz::ControlPanel::load(const rviz_common::Config &config) override
References activeBallastEnabled, auxPub, ballastLogRunning, calibrateDrag, clawObjectPub, ctrlCmdAngPub, ctrlCmdLinPub, diagCallback, diagSub, dragCalTriggerPub, exaustSolenoidCb, exaustSolenoidPub, exaustSolenoidSub, get_hostname, hostname, interactiveSetpointMarker, killPubTimer, killStatePub, last_duplicate_state, lastBallastLogTime, lastCommandedPose, max_depth_in_place, odom_timeout, odomCallback, odomSub, pressureSolenoidCb, pressureSolenoidPub, pressureSolenoidSub, pubCurrentSetpoint, refreshUI, regHousingPressureCallback, regHousingPressureSub, regPressureCallback, regPressureSub, reloadCompleteClient, reloadLiltankClient, robot_ns, selectedPose, selectPoseSub, sendKillMsgTimer, SETPOINT_MARKER_SCALE, SETPOINT_REPUB_PERIOD, setPointPubTimer, setptServer, setSimPoseClient, setTeleopClient, tankPressureCallback, tankPressureSub, tf_buffer, tf_listener, tgt_in_place_depth, uiPanel, uiTimer, waterSolenoidCb, waterSolenoidPub, waterSolenoidSub.
void riptide_rviz::ControlPanel::save(rviz_common::Config config) const override
References max_depth_in_place, odom_timeout, robot_ns, tgt_in_place_depth.
void riptide_rviz::ControlPanel::onInitialize() override
References ballastDiagram, handleAuxDown, handleAuxUp, handleBallastDive, handleBallastHold, handleBallastSurface, handleBallastToggleExaust, handleBallastTogglePressure, handleBallastToggleWater, handleCurrent, handleDisable, handleEnable, handleLocalDive, handleReloadController, handleStartDragCal, handleStopDragCal, handleTriggerDragCal, simulator_apply_clickec, startBallastLogData, toggleDegrees, uiPanel.
void riptide_rviz::ControlPanel::odomCallback(const nav_msgs::msg::Odometry &msg)
References ballastLogData, ballastLogRunning, degreeReadout, odom_timeout, odomTime, transformBetweenFrames, uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::diagCallback(const diagnostic_msgs::msg::DiagnosticArray &msg)
References uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::selectedPose(const geometry_msgs::msg::PoseStamped &msg)
References ctrlMode, degreeReadout, POSITION, uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::sendKillMsgTimer()
References hostname, killStatePub, uiPanel, vehicleEnabled.
Referenced by load.
void riptide_rviz::ControlPanel::handleEnable()
References uiPanel, vehicleEnabled.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleDisable()
References ctrlCmdAngPub, ctrlCmdLinPub, DISABLED, switchMode, uiPanel, vehicleEnabled.
Referenced by onInitialize, refreshUI.
void riptide_rviz::ControlPanel::switchMode(uint8_t mode, bool override=false)
References callSetBoolService, ctrlMode, DISABLED, FEEDFORWARD, handleCommand, interactiveSetpointMarker, POSITION, robot_ns, setptMarkerFeedback, setptServer, setTeleopClient, syncSetptMarkerToTextboxes, TELEOP, teleopPID, uiPanel, vehicleEnabled, VELOCITY.
Referenced by handleDisable.
void riptide_rviz::ControlPanel::handleAuxDown()
References auxPub.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleAuxUp()
References auxPub.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::toggleDegrees()
References degreeReadout, uiPanel.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::refreshUI()
References ballastLogRunning, checkForDuplicateTopics, displayPopupWindow, duplicate_topics_list, handleDisable, last_duplicate_state, max_depth_in_place, odom_timeout, odomTime, uiPanel, updateBallastLog, vehicleEnabled.
Referenced by load.
void riptide_rviz::ControlPanel::handleLocalDive()
References handleCommand, uiPanel.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleCurrent()
References syncSetptMarkerToTextboxes, uiPanel.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleCommand(bool updateInteractiveMarker)
References ctrlCmdAngPub, ctrlCmdLinPub, ctrlMode, degreeReadout, FEEDFORWARD, getDesiredSetpointFromTextboxes, lastCommandedPose, POSITION, syncSetptMarkerToTextboxes, transformBetweenFrames, uiPanel.
Referenced by handleLocalDive, setptMarkerFeedback, switchMode.
void riptide_rviz::ControlPanel::handleReloadController()
References callTriggerService, reloadCompleteClient, reloadLiltankClient, uiPanel, updateCalStatus.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleStartDragCal()
References calibrateDrag, dragGoalResponseCb, dragResultCb, setDragCalRunning, uiPanel, updateCalStatus.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleStopDragCal()
References calibrateDrag.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleTriggerDragCal()
References dragCalTriggerPub.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::simulator_apply_clickec()
References clawObjectPub, uiPanel.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastDive()
References publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastSurface()
References publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastHold()
References publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastToggleExaust()
References getSolenoidStatuses, isBallastStateIllegal, publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastTogglePressure()
References getSolenoidStatuses, isBallastStateIllegal, publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::handleBallastToggleWater()
References getSolenoidStatuses, isBallastStateIllegal, publishSolenoidStatuses.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::startBallastLogData()
References ballastLogData, ballastLogFileName, ballastLogRunning, uiPanel.
Referenced by onInitialize.
void riptide_rviz::ControlPanel::pubCurrentSetpoint()
References ctrlMode, lastCommandedPose, POSITION.
Referenced by load.
bool riptide_rviz::ControlPanel::event(QEvent *event)
References ballastDiagram, event, uiPanel.
Referenced by event.
bool riptide_rviz::ControlPanel::transformBetweenFrames(geometry_msgs::msg::Pose pose_in, geometry_msgs::msg::Pose &pose_out, const std::string &from_frame, const std::string &to_frame)
References tf_buffer.
Referenced by handleCommand, odomCallback, syncSetptMarkerToTextboxes.
bool riptide_rviz::ControlPanel::getDesiredSetpointFromTextboxes(double results[6])
Populates the results array with the values of the setpoint number boxes. Ordered xyzrpw
References uiPanel.
Referenced by handleCommand, syncSetptMarkerToTextboxes.
void riptide_rviz::ControlPanel::syncSetptMarkerToTextboxes(bool applyChanges=true)
References degreeReadout, getDesiredSetpointFromTextboxes, interactiveSetpointMarker, setptServer, transformBetweenFrames, uiPanel.
Referenced by handleCommand, handleCurrent, switchMode.
void riptide_rviz::ControlPanel::setptMarkerFeedback(interactive_markers::InteractiveMarkerServer::FeedbackConstSharedPtr feedback)
invoked when the interactive setpoint marker is moved
feedback feedback containing the new pose
References degreeReadout, handleCommand, uiPanel.
Referenced by switchMode.
void riptide_rviz::ControlPanel::updateCalStatus(const std::string &status)
References uiPanel.
Referenced by callTriggerService, dragGoalResponseCb, dragResultCb, handleReloadController, handleStartDragCal, waitForSetBoolResponse, waitForTriggerResponse.
void riptide_rviz::ControlPanel::callTriggerService(rclcpp::Client< Trigger >::SharedPtr client)
References activeClientFuture, clientSendTime, srvReqId, updateCalStatus, waitForTriggerResponse.
Referenced by handleReloadController.
void riptide_rviz::ControlPanel::callSetBoolService(rclcpp::Client< SetBool >::SharedPtr client, bool value)
References activeSetBoolClientFuture, clientSendTime, srvReqId, waitForSetBoolResponse.
Referenced by switchMode.
void riptide_rviz::ControlPanel::callSetPoseService(rclcpp::Client< SetPose >::SharedPtr client, std::vector< double > pose)
References activeSetPoseClientFuture, clientSendTime, srvReqId, waitForSetPoseResponse.
void riptide_rviz::ControlPanel::waitForTriggerResponse(rclcpp::Client< Trigger >::SharedPtr client)
References activeClientFuture, clientSendTime, srvReqId, updateCalStatus, waitForTriggerResponse.
Referenced by callTriggerService, waitForTriggerResponse.
void riptide_rviz::ControlPanel::waitForSetBoolResponse(rclcpp::Client< SetBool >::SharedPtr client)
References activeSetBoolClientFuture, clientSendTime, srvReqId, updateCalStatus, waitForSetBoolResponse.
Referenced by callSetBoolService, waitForSetBoolResponse.
void riptide_rviz::ControlPanel::waitForSetPoseResponse(rclcpp::Client< SetPose >::SharedPtr client)
References activeSetPoseClientFuture, clientSendTime, srvReqId, waitForSetPoseResponse.
Referenced by callSetPoseService, waitForSetPoseResponse.
void riptide_rviz::ControlPanel::setDragCalRunning(bool running)
References uiPanel.
Referenced by dragGoalResponseCb, dragResultCb, handleStartDragCal.
void riptide_rviz::ControlPanel::dragGoalResponseCb(const CalibrateDragGH::SharedPtr &goal_handle)
References setDragCalRunning, updateCalStatus.
Referenced by handleStartDragCal.
void riptide_rviz::ControlPanel::dragResultCb(const CalibrateDragGH::WrappedResult &result)
References setDragCalRunning, updateCalStatus.
Referenced by handleStartDragCal.
void riptide_rviz::ControlPanel::setSolenoidStatuses(const bool statuses[3])
References uiPanel.
Referenced by exaustSolenoidCb, pressureSolenoidCb, waterSolenoidCb.
void riptide_rviz::ControlPanel::getSolenoidStatuses(bool statuses[3])
References uiPanel.
Referenced by exaustSolenoidCb, handleBallastToggleExaust, handleBallastTogglePressure, handleBallastToggleWater, pressureSolenoidCb, waterSolenoidCb.
void riptide_rviz::ControlPanel::publishSolenoidStatuses(const bool statuses[3])
References exaustSolenoidPub, pressureSolenoidPub, waterSolenoidPub.
Referenced by handleBallastDive, handleBallastHold, handleBallastSurface, handleBallastToggleExaust, handleBallastTogglePressure, handleBallastToggleWater.
bool riptide_rviz::ControlPanel::isBallastStateIllegal(bool statuses[3])
Referenced by handleBallastToggleExaust, handleBallastTogglePressure, handleBallastToggleWater.
void riptide_rviz::ControlPanel::exaustSolenoidCb(const std_msgs::msg::Bool &msg)
References ballastLogData, ballastLogRunning, getSolenoidStatuses, setSolenoidStatuses.
Referenced by load.
void riptide_rviz::ControlPanel::pressureSolenoidCb(const std_msgs::msg::Bool &msg)
References ballastLogData, ballastLogRunning, getSolenoidStatuses, setSolenoidStatuses.
Referenced by load.
void riptide_rviz::ControlPanel::waterSolenoidCb(const std_msgs::msg::Bool &msg)
References ballastLogData, ballastLogRunning, getSolenoidStatuses, setSolenoidStatuses.
Referenced by load.
void riptide_rviz::ControlPanel::regPressureCallback(const std_msgs::msg::Float32 &msg)
References ballastLogData, ballastLogRunning, uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::regHousingPressureCallback(const std_msgs::msg::Float32 &msg)
References ballastLogData, ballastLogRunning, uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::tankPressureCallback(const std_msgs::msg::Float32 &msg)
References ballastLogData, ballastLogRunning, uiPanel.
Referenced by load.
void riptide_rviz::ControlPanel::updateBallastLog(const rclcpp::Time &now)
References ballastLogData, ballastLogFileName, lastBallastLogTime.
Referenced by refreshUI.
void riptide_rviz::ControlPanel::displayPopupWindow(const std::string &warningMessage, const std::string &text)
Referenced by refreshUI.
bool riptide_rviz::ControlPanel::checkForDuplicateTopics()
References duplicate_topics_list, topic_duplicate_status.
Referenced by refreshUI.