riptide_rviz::ParamPanel
bool riptide_rviz::ParamPanel::loaded
Referenced by load.
bool riptide_rviz::ParamPanel::connected
Referenced by getParams, setNode.
std::shared_ptr<rclcpp::Node> riptide_rviz::ParamPanel::node
Referenced by getNodes, load, setNode.
std::shared_ptr<rclcpp::SyncParametersClient> riptide_rviz::ParamPanel::param_client
Referenced by apply, getParams, setNode.
QComboBox* riptide_rviz::ParamPanel::nodes
Referenced by getNodes, onInitialize, ParamPanel, refresh.
QLineEdit* riptide_rviz::ParamPanel::searchBox
Referenced by onInitialize, ParamPanel, setNode.
QWidget* riptide_rviz::ParamPanel::searchContainer
Referenced by createParams, ParamPanel, setNode.
QVBoxLayout* riptide_rviz::ParamPanel::paramLayout
Referenced by apply, createParams, filterParameters, ParamPanel, setNode.
QPushButton* riptide_rviz::ParamPanel::applyButton
Referenced by onInitialize, ParamPanel.
QPushButton* riptide_rviz::ParamPanel::refreshButton
Referenced by onInitialize, ParamPanel.
QStatusBar* riptide_rviz::ParamPanel::statusBar
Referenced by ParamPanel, showStatusMessage.
QString riptide_rviz::ParamPanel::robotNs
Referenced by load, save.
QMap<QString, QVariant> riptide_rviz::ParamPanel::originalValues
Referenced by apply, createParams, highlightChanges, storeOriginalValue.
QMap<QString, QWidget*> riptide_rviz::ParamPanel::arrayContainers
riptide_rviz::ParamPanel::ParamPanel(QWidget *parent=0)
References applyButton, nodes, paramLayout, refreshButton, searchBox, searchContainer, statusBar.
riptide_rviz::ParamPanel::~ParamPanel()
void riptide_rviz::ParamPanel::load(const rviz_common::Config &config) override
References getNodes, loaded, node, robotNs.
void riptide_rviz::ParamPanel::save(rviz_common::Config config) const override
References robotNs.
void riptide_rviz::ParamPanel::onInitialize() override
References apply, applyButton, filterParameters, nodes, refresh, refreshButton, searchBox, setNode.
void riptide_rviz::ParamPanel::apply()
References getCurrentValue, originalValues, param_client, paramLayout, showStatusMessage.
Referenced by onInitialize.
void riptide_rviz::ParamPanel::setNode(const QString &text)
References connected, createParams, eraseLayout, getParams, node, param_client, paramLayout, searchBox, searchContainer, showStatusMessage.
Referenced by onInitialize, refresh.
void riptide_rviz::ParamPanel::refresh()
References getNodes, nodes, setNode, showStatusMessage.
Referenced by onInitialize.
void riptide_rviz::ParamPanel::filterParameters(const QString &text)
References paramLayout.
Referenced by onInitialize.
void riptide_rviz::ParamPanel::parameterValueChanged()
References highlightChanges.
Referenced by createParams.
void riptide_rviz::ParamPanel::showStatusMessage(const QString &message, int timeout=3000)
References statusBar.
Referenced by apply, getParams, refresh, setNode.
void riptide_rviz::ParamPanel::getNodes()
References node, nodes.
Referenced by load, refresh.
std::vector< rclcpp::Parameter > riptide_rviz::ParamPanel::getParams()
References connected, param_client, showStatusMessage.
Referenced by setNode.
void riptide_rviz::ParamPanel::createParams(std::vector< rclcpp::Parameter > params)
References originalValues, parameterValueChanged, paramLayout, searchContainer, storeOriginalValue.
Referenced by setNode.
void riptide_rviz::ParamPanel::eraseLayout(QLayout *layout)
References eraseLayout.
Referenced by eraseLayout, setNode.
void riptide_rviz::ParamPanel::storeOriginalValue(QWidget *widget, const QString &name)
References getCurrentValue, originalValues.
Referenced by createParams.
void riptide_rviz::ParamPanel::highlightChanges(QWidget *widget, const QString &name)
References getCurrentValue, originalValues.
Referenced by parameterValueChanged.
QVariant riptide_rviz::ParamPanel::getCurrentValue(QWidget *widget)
Referenced by apply, highlightChanges, storeOriginalValue.
bool riptide_rviz::ParamPanel::eventFilter(QObject *obj, QEvent *event) override