riptide_rviz::Actuators
Ui_Actuators* riptide_rviz::Actuators::uiPanel
Referenced by Actuators, onInitialize, statusCallback, updateStatus, ~Actuators.
std::string riptide_rviz::Actuators::robotNs
Referenced by load, save.
rclcpp::Subscription<ActuatorStatus>::SharedPtr riptide_rviz::Actuators::statusSub
Referenced by load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::dropperTopic
Referenced by handleDropMarker, load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::torpedoTopic
Referenced by handleFireTorpedo, load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::reloadTopic
Referenced by handleReload, load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::torpMarkerGoHomeTopic
Referenced by handleTorpGoHome, load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::torpMarkerSetHomeTopic
Referenced by handleTorpSetHome, load.
rclcpp::Publisher<Empty>::SharedPtr riptide_rviz::Actuators::clawSetClosedPosTopic
Referenced by handleClawSetHome, load.
rclcpp::Publisher<Bool>::SharedPtr riptide_rviz::Actuators::armTopic
Referenced by handleArm, handleDisarm, load.
rclcpp::Publisher<Bool>::SharedPtr riptide_rviz::Actuators::clawTopic
Referenced by handleCloseClaw, handleOpenClaw, load.
rclcpp::Subscription<std_msgs::msg::String>::SharedPtr riptide_rviz::Actuators::cmdFeedback
rclcpp::Subscription<Bool>::SharedPtr riptide_rviz::Actuators::cmdStatus
std::string riptide_rviz::Actuators::latestCmdFeedback
Referenced by cmdFeedbackCb, updateStatus.
bool riptide_rviz::Actuators::latestCmdStatus
Referenced by cmdStatusCb, updateStatus.
riptide_rviz::Actuators::Actuators(QWidget *parent=0)
References uiPanel.
riptide_rviz::Actuators::~Actuators()
References uiPanel.
void riptide_rviz::Actuators::load(const rviz_common::Config &config) override
References armTopic, clawSetClosedPosTopic, clawTopic, dropperTopic, reloadTopic, robotNs, statusCallback, statusSub, torpedoTopic, torpMarkerGoHomeTopic, torpMarkerSetHomeTopic.
void riptide_rviz::Actuators::save(rviz_common::Config config) const override
References robotNs.
void riptide_rviz::Actuators::onInitialize() override
References handleArm, handleClawGoHome, handleClawSetHome, handleCloseClaw, handleDisarm, handleDropMarker, handleFireTorpedo, handleOpenClaw, handleReload, handleTorpGoHome, handleTorpSetHome, uiPanel.
void riptide_rviz::Actuators::handleArm()
References armTopic, pubBoolTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleDisarm()
References armTopic, pubBoolTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleOpenClaw()
References clawTopic, pubBoolTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleCloseClaw()
References clawTopic, pubBoolTopic.
Referenced by handleClawGoHome, onInitialize.
void riptide_rviz::Actuators::handleFireTorpedo()
References pubEmptyTopic, torpedoTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleDropMarker()
References dropperTopic, pubEmptyTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleReload()
References pubEmptyTopic, reloadTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleClawGoHome()
References handleCloseClaw.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleClawSetHome()
References clawSetClosedPosTopic, pubEmptyTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleTorpGoHome()
References pubEmptyTopic, torpMarkerGoHomeTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::handleTorpSetHome()
References pubEmptyTopic, torpMarkerSetHomeTopic.
Referenced by onInitialize.
void riptide_rviz::Actuators::statusCallback(const riptide_msgs2::msg::ActuatorStatus::SharedPtr msg)
References riptide_rviz::CLAW_STATUSES, riptide_rviz::DROPPER_STATUSES, riptide_rviz::STATUS_ERROR_STYLESHEET, riptide_rviz::STATUS_GOOD_STYLESHEET, riptide_rviz::TORPEDO_STATUSES, uiPanel.
Referenced by load.
void riptide_rviz::Actuators::updateStatus()
References latestCmdFeedback, latestCmdStatus, uiPanel.
Referenced by cmdFeedbackCb, cmdStatusCb.
void riptide_rviz::Actuators::cmdFeedbackCb(const std_msgs::msg::String::SharedPtr msg)
References latestCmdFeedback, updateStatus.
void riptide_rviz::Actuators::cmdStatusCb(const Bool::SharedPtr msg)
References latestCmdStatus, updateStatus.
void riptide_rviz::Actuators::pubEmptyTopic(rclcpp::Publisher< Empty >::SharedPtr pub)
Referenced by handleClawSetHome, handleDropMarker, handleFireTorpedo, handleReload, handleTorpGoHome, handleTorpSetHome.
void riptide_rviz::Actuators::pubBoolTopic(rclcpp::Publisher< Bool >::SharedPtr pub, bool value)
Referenced by handleArm, handleCloseClaw, handleDisarm, handleOpenClaw.