riptide_rviz::MissionPanel
Ui_MissionPanel* riptide_rviz::MissionPanel::uiPanel
Referenced by handleSelectTree, MissionPanel, onInitialize, refresh, startTask, taskCompleteCb, taskStartCb, updateLedReadout, waitForRefresh, ~MissionPanel.
QStandardItemModel* riptide_rviz::MissionPanel::model
Referenced by onInitialize, stackCb, ~MissionPanel.
std::vector<std::string> riptide_rviz::MissionPanel::treeList
Referenced by handleSelectTree, MissionPanel, waitForRefresh.
riptide_msgs2::msg::LedCommand riptide_rviz::MissionPanel::lastLedCommand
Referenced by ledCb, updateLedReadout.
rclcpp::TimerBase::SharedPtr riptide_rviz::MissionPanel::ledTimer
Referenced by load.
rclcpp::Subscription<riptide_msgs2::msg::TreeStack>::SharedPtr riptide_rviz::MissionPanel::stackSub
Referenced by load, ~MissionPanel.
rclcpp::Subscription<riptide_msgs2::msg::LedCommand>::SharedPtr riptide_rviz::MissionPanel::ledSub
Referenced by load.
rclcpp::Client<riptide_msgs2::srv::ListTrees>::SharedPtr riptide_rviz::MissionPanel::refreshClient
Referenced by load, refresh, waitForRefresh, ~MissionPanel.
std::shared_future<std::shared_ptr<riptide_msgs2::srv::ListTrees_Response> > riptide_rviz::MissionPanel::refreshFuture
Referenced by refresh, waitForRefresh.
int64_t riptide_rviz::MissionPanel::refreshFutureid
Referenced by refresh, waitForRefresh.
int riptide_rviz::MissionPanel::timerTick
Referenced by refresh, waitForRefresh.
rclcpp_action::Client<ExecuteTree>::SharedPtr riptide_rviz::MissionPanel::actionServer
Referenced by cancelTask, load, startTask, ~MissionPanel.
std::string riptide_rviz::MissionPanel::robot_ns
Referenced by load, save.
riptide_rviz::MissionPanel::MissionPanel(QWidget *parent=0)
References treeList, uiPanel.
riptide_rviz::MissionPanel::~MissionPanel()
References actionServer, model, refreshClient, stackSub, uiPanel.
void riptide_rviz::MissionPanel::load(const rviz_common::Config &config) override
References actionServer, ledCb, ledSub, ledTimer, refresh, refreshClient, robot_ns, stackCb, stackSub, updateLedReadout.
void riptide_rviz::MissionPanel::save(rviz_common::Config config) const override
References robot_ns.
void riptide_rviz::MissionPanel::onInitialize() override
References handleSelectTree, model, uiPanel.
void riptide_rviz::MissionPanel::refresh()
References refreshClient, refreshFuture, refreshFutureid, timerTick, uiPanel, waitForRefresh.
Referenced by load.
void riptide_rviz::MissionPanel::handleSelectTree(int)
References treeList, uiPanel.
Referenced by onInitialize.
void riptide_rviz::MissionPanel::startTask()
References actionServer, taskCompleteCb, taskFeedbackCb, taskStartCb, uiPanel.
void riptide_rviz::MissionPanel::cancelTask()
References actionServer, cancelAccept.
bool riptide_rviz::MissionPanel::event(QEvent *event)
References event.
Referenced by event.
void riptide_rviz::MissionPanel::taskStartCb(const GHExecuteTree::SharedPtr &goalHandle)
References uiPanel.
Referenced by startTask.
void riptide_rviz::MissionPanel::cancelAccept(const action_msgs::srv::CancelGoal::Response::SharedPtr)
Referenced by cancelTask.
void riptide_rviz::MissionPanel::taskCompleteCb(const GHExecuteTree::WrappedResult &result)
References uiPanel.
Referenced by startTask.
void riptide_rviz::MissionPanel::taskFeedbackCb(GHExecuteTree::SharedPtr goalHandle, ExecuteTree::Feedback::ConstSharedPtr feedback)
Referenced by startTask.
void riptide_rviz::MissionPanel::stackCb(const riptide_msgs2::msg::TreeStack &stack)
References model.
Referenced by load.
void riptide_rviz::MissionPanel::ledCb(const riptide_msgs2::msg::LedCommand &cmd)
References lastLedCommand.
Referenced by load.
void riptide_rviz::MissionPanel::waitForRefresh(void)
References refreshClient, refreshFuture, refreshFutureid, timerTick, treeList, uiPanel, waitForRefresh.
Referenced by refresh, waitForRefresh.
void riptide_rviz::MissionPanel::updateLedReadout(void)
References lastLedCommand, uiPanel.
Referenced by load.