riptide_rviz::BagItem
Ui_BagListElement* riptide_rviz::BagItem::uiPanel
Referenced by baggingConfigure, BagItem, getName, shutdownTimer, startBagging, startupTimer, stateChanging, stateRunning, stateStopped, stopBagging, ~BagItem.
std::vector<launch_msgs::msg::TopicData> riptide_rviz::BagItem::topics
Referenced by loadTopics, startBagging.
std::shared_ptr<RecipeBag> riptide_rviz::BagItem::bagData
Referenced by baggingConfigure, BagItem.
rclcpp::Client<launch_msgs::srv::StartBag>::SharedPtr riptide_rviz::BagItem::bagStartClient
Referenced by BagItem, startBagging, startupTimer, stopBagging.
rclcpp::Client<launch_msgs::srv::StopBag>::SharedPtr riptide_rviz::BagItem::bagStopClient
Referenced by BagItem, shutdownTimer, stopBagging.
std::shared_future<std::shared_ptr<launch_msgs::srv::StartBag_Response> > riptide_rviz::BagItem::startFuture
Referenced by startBagging, startupTimer.
std::shared_future<std::shared_ptr<launch_msgs::srv::StopBag_Response> > riptide_rviz::BagItem::stopFuture
Referenced by shutdownTimer, stopBagging.
int64_t riptide_rviz::BagItem::startReqId
Referenced by isStarting, startBagging, startupTimer.
int64_t riptide_rviz::BagItem::stopReqId
Referenced by isStopping, shutdownTimer, stopBagging.
int riptide_rviz::BagItem::timerTick
Referenced by shutdownTimer, startBagging, startupTimer, stopBagging.
int riptide_rviz::BagItem::pid
Referenced by bagAlive, BagItem, getPid, shutdownTimer, startBagging, startupTimer, stopBagging.
bool riptide_rviz::BagItem::isLocal
Referenced by BagItem, local, startBagging, stateStopped.
riptide_rviz::BagItem::BagItem(std::string hostName, std::shared_ptr< RecipeBag > bagData, std::shared_ptr< rclcpp::Node > parentNode, int local=-1)
References bagData, bagStartClient, bagStopClient, isLocal, loadTopics, local, pid, stateRunning, stateStopped, uiPanel.
riptide_rviz::BagItem::~BagItem()
References uiPanel.
bool riptide_rviz::BagItem::bagAlive(std::vector< int > bids)
References pid, stateStopped.
void riptide_rviz::BagItem::getName(std::string &name)
References uiPanel.
Referenced by startBagging.
int riptide_rviz::BagItem::getPid()
References pid.
bool riptide_rviz::BagItem::local()
References isLocal.
Referenced by BagItem.
void riptide_rviz::BagItem::startBagging()
References bagStartClient, getName, isLocal, pid, startFuture, startReqId, startupTimer, stateChanging, timerTick, topics, uiPanel.
bool riptide_rviz::BagItem::isStarting()
References startReqId.
void riptide_rviz::BagItem::stopBagging()
References bagStartClient, bagStopClient, pid, shutdownTimer, stateChanging, stopFuture, stopReqId, timerTick, uiPanel.
bool riptide_rviz::BagItem::isStopping()
References stopReqId.
bool riptide_rviz::BagItem::event(QEvent *event)
References event.
Referenced by event.
void riptide_rviz::BagItem::baggingConfigure()
References bagData, loadTopics, uiPanel.
void riptide_rviz::BagItem::startupTimer()
References bagStartClient, pid, startFuture, startReqId, startupTimer, stateRunning, stateStopped, timerTick, uiPanel.
Referenced by startBagging, startupTimer.
void riptide_rviz::BagItem::shutdownTimer()
References bagStopClient, pid, shutdownTimer, stateStopped, stopFuture, stopReqId, timerTick, uiPanel.
Referenced by shutdownTimer, stopBagging.
void riptide_rviz::BagItem::stateStopped()
References isLocal, uiPanel.
Referenced by bagAlive, BagItem, shutdownTimer, startupTimer.
void riptide_rviz::BagItem::stateChanging()
References uiPanel.
Referenced by startBagging, stopBagging.
void riptide_rviz::BagItem::stateRunning()
References uiPanel.
Referenced by BagItem, startupTimer.
void riptide_rviz::BagItem::loadTopics(const std::vector< RecipeTopicData > &topicList)
References topics.
Referenced by baggingConfigure, BagItem.