riptide_rviz::ScopedPixelBuffer
Ogre::HardwarePixelBufferSharedPtr riptide_rviz::ScopedPixelBuffer::pixel_buffer_
Referenced by getPixelBuffer, getQImage, ScopedPixelBuffer, ~ScopedPixelBuffer.
riptide_rviz::ScopedPixelBuffer::ScopedPixelBuffer(Ogre::HardwarePixelBufferSharedPtr pixel_buffer)
References pixel_buffer_.
riptide_rviz::ScopedPixelBuffer::~ScopedPixelBuffer()
References pixel_buffer_.
Ogre::HardwarePixelBufferSharedPtr riptide_rviz::ScopedPixelBuffer::getPixelBuffer()
References pixel_buffer_.
QImage riptide_rviz::ScopedPixelBuffer::getQImage(unsigned int width, unsigned int height)
References pixel_buffer_.
Referenced by getQImage, getQImage, getQImage, riptide_rviz::OverlayDisplay::update.
QImage riptide_rviz::ScopedPixelBuffer::getQImage(OverlayObject &overlay)
References getQImage, riptide_rviz::OverlayObject::getTextureHeight, riptide_rviz::OverlayObject::getTextureWidth.
QImage riptide_rviz::ScopedPixelBuffer::getQImage(unsigned int width, unsigned int height, QColor &bg_color)
References getQImage.
QImage riptide_rviz::ScopedPixelBuffer::getQImage(OverlayObject &overlay, QColor &bg_color)
References getQImage, riptide_rviz::OverlayObject::getTextureHeight, riptide_rviz::OverlayObject::getTextureWidth.