riptide_rviz::Recipe
std::map<std::string, RecipeStage> riptide_rviz::Recipe::stages
Referenced by getLaunchOrder, loadXml, operator==, stageExists, walkDependencyTree.
std::vector<std::shared_ptr<RecipeLaunch> > riptide_rviz::Recipe::launches
Referenced by getAllLaunches, operator==, parseStageTag.
RecipeXMLError riptide_rviz::Recipe::loadXml(std::string const &recipePath)
References riptide_rviz::RecipeStage::dependencies, riptide_rviz::DEPENDENCY_CYCLE, riptide_rviz::EMPTY_RECIPE, riptide_rviz::RecipeXMLError::errorCode, riptide_rviz::RecipeStage::id, riptide_rviz::NO_LAUNCHES_TAG, riptide_rviz::NON_EXISTANT_DEPENDENCY, parseStageTag, stageExists, stages, riptide_rviz::SUCCESS, walkDependencyTree.
std::vector< std::shared_ptr< RecipeLaunch > > riptide_rviz::Recipe::getAllLaunches()
References getAllLaunches, launches.
Referenced by getAllLaunches.
std::vector< std::vector< int > > riptide_rviz::Recipe::getLaunchOrder()
References getLaunchOrder, stages.
Referenced by getLaunchOrder.
std::vector< std::shared_ptr< RecipeBag > > riptide_rviz::Recipe::getAllBags()
References operator!=, operator==.
bool riptide_rviz::Recipe::operator==(const Recipe &)
References launches, stages.
Referenced by getAllBags, operator!=.
bool riptide_rviz::Recipe::operator!=(const Recipe &)
References operator==.
Referenced by getAllBags.
RecipeXMLError riptide_rviz::Recipe::parseStageTag(const tinyxml2::XMLElement *stageXML, RecipeStage &stage)
References riptide_rviz::DUPLICATE_NAMES, riptide_rviz::DUPLICATE_STAGE_IDS, riptide_rviz::RecipeXMLError::errorCode, riptide_rviz::RecipeStage::id, launches, riptide_rviz::RecipeStage::launchIndicies, riptide_rviz::MISSING_ID_ATTRIBUTE, riptide_rviz::RecipeLaunch::name, riptide_rviz::NON_STAGE_TAG, parseDependencyTag, parseLaunchTag, riptide_rviz::STAGE_WITH_NO_LAUNCH, stageExists, riptide_rviz::SUCCESS, riptide_rviz::UNKNOWN_TAG_TYPE.
Referenced by loadXml.
RecipeXMLError riptide_rviz::Recipe::parseDependencyTag(const tinyxml2::XMLElement *dependsXML, RecipeStage &stage)
References riptide_rviz::RecipeStage::dependencies, riptide_rviz::MISSING_ID_ATTRIBUTE, riptide_rviz::SUCCESS.
Referenced by parseStageTag.
RecipeXMLError riptide_rviz::Recipe::parseLaunchTag(const tinyxml2::XMLElement *launchXML, const char *stageID, RecipeLaunch &launch)
References riptide_rviz::RecipeLaunch::arguments, riptide_rviz::MISSING_NAME_ATTRIBUTE, riptide_rviz::MISSING_PACKAGE_ATTRIBUTE, riptide_rviz::MISSING_VALUE_ATTRIBUTE, riptide_rviz::RecipeLaunch::name, riptide_rviz::RecipeLaunch::package, riptide_rviz::RecipeLaunch::stageID, riptide_rviz::UNKNOWN_TAG_TYPE.
Referenced by parseStageTag.
bool riptide_rviz::Recipe::stageExists(const char *stageID)
References stages.
Referenced by loadXml, parseStageTag.
void riptide_rviz::Recipe::walkDependencyTree(const std::string &stageID, std::set< std::string > &dependencyWalkResults)
Walks through the dependency tree of a certain stage id This function fills out the dependencyWalkResults with all the dependencies a stage relies, either indirectly. This is used to check for dependency cycles.
References riptide_rviz::RecipeStage::dependencies, stages, walkDependencyTree.
Referenced by loadXml, walkDependencyTree.