riptide_rviz::DiagnosticsPanel
Ui::DiagnosticsPanel* riptide_rviz::DiagnosticsPanel::uiPanel
Referenced by diagCb, DiagnosticsPanel, onInitialize, ~DiagnosticsPanel.
QStandardItemModel* riptide_rviz::DiagnosticsPanel::model
Referenced by diagCb, DiagnosticsPanel, onInitialize, refresh.
std::string riptide_rviz::DiagnosticsPanel::robot_ns
Referenced by load, save.
QMap<int, QIcon> riptide_rviz::DiagnosticsPanel::statusIcons
Referenced by createStatusIcons, diagCb.
rclcpp::Subscription<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr riptide_rviz::DiagnosticsPanel::diagSub
Referenced by load, ~DiagnosticsPanel.
int riptide_rviz::DiagnosticsPanel::timerTick
Referenced by diagCb, DiagnosticsPanel, refresh.
riptide_rviz::DiagnosticsPanel::DiagnosticsPanel(QWidget *parent=nullptr)
References createStatusIcons, model, timerTick, uiPanel.
riptide_rviz::DiagnosticsPanel::~DiagnosticsPanel() override
References diagSub, uiPanel.
void riptide_rviz::DiagnosticsPanel::onInitialize() override
References model, uiPanel.
void riptide_rviz::DiagnosticsPanel::load(const rviz_common::Config &config) override
References diagCb, diagSub, refresh, robot_ns.
void riptide_rviz::DiagnosticsPanel::save(rviz_common::Config config) const override
References robot_ns.
bool riptide_rviz::DiagnosticsPanel::event(QEvent *event) override
References event.
Referenced by event.
void riptide_rviz::DiagnosticsPanel::refresh()
References model, timerTick.
Referenced by diagCb, load.
void riptide_rviz::DiagnosticsPanel::waitForRefresh()
void riptide_rviz::DiagnosticsPanel::createStatusIcons()
References statusIcons.
Referenced by DiagnosticsPanel.
void riptide_rviz::DiagnosticsPanel::findMatchingItems(QStandardItem *item, const QString &path, QList< QStandardItem * > &results)
References findMatchingItems.
Referenced by diagCb, findMatchingItems.
void riptide_rviz::DiagnosticsPanel::diagCb(const diagnostic_msgs::msg::DiagnosticArray &msg)
References findMatchingItems, model, refresh, statusIcons, timerTick, uiPanel.
Referenced by load.