riptide_rviz::DiagnosticOverlay
rclcpp::TimerBase::SharedPtr riptide_rviz::DiagnosticOverlay::checkTimer
Referenced by onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastDiag
Referenced by checkTimeout, diagnosticCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastKill
Referenced by checkTimeout, killCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastZed
Referenced by checkTimeout, onInitialize, zedCallback.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastDfc
Referenced by checkTimeout, dfcCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastLeak
Referenced by checkTimeout, leakCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastGyro
Referenced by checkTimeout, gyroCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastPressure
Referenced by checkTimeout, onInitialize, pressureCallback.
rclcpp::Time riptide_rviz::DiagnosticOverlay::lastCpuTemp
Referenced by checkTimeout, diagnosticCallback, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::stbdlastBattery
Referenced by batteryCallback, checkTimeout, onInitialize.
rclcpp::Time riptide_rviz::DiagnosticOverlay::portlastBattery
Referenced by batteryCallback, checkTimeout, onInitialize.
bool riptide_rviz::DiagnosticOverlay::diagsTimedOut
Referenced by checkTimeout, diagnosticCallback.
bool riptide_rviz::DiagnosticOverlay::killTimedOut
Referenced by checkTimeout, killCallback.
bool riptide_rviz::DiagnosticOverlay::zedTimedOut
Referenced by checkTimeout, zedCallback.
bool riptide_rviz::DiagnosticOverlay::dfcTimedOut
Referenced by checkTimeout, dfcCallback.
bool riptide_rviz::DiagnosticOverlay::leakTimedOut
Referenced by checkTimeout, leakCallback.
bool riptide_rviz::DiagnosticOverlay::gyroTimedOut
Referenced by checkTimeout, gyroCallback.
bool riptide_rviz::DiagnosticOverlay::pressureTimedOut
Referenced by checkTimeout, pressureCallback.
bool riptide_rviz::DiagnosticOverlay::cpuTempTimedOut
Referenced by checkTimeout, diagnosticCallback.
bool riptide_rviz::DiagnosticOverlay::stbdBatteryTimedOut
Referenced by batteryCallback, checkTimeout.
bool riptide_rviz::DiagnosticOverlay::portBatteryTimedOut
Referenced by batteryCallback, checkTimeout.
bool riptide_rviz::DiagnosticOverlay::startedLeaking
Referenced by leakCallback.
bool riptide_rviz::DiagnosticOverlay::redFlash
Referenced by leakCallback, pressureCallback.
rclcpp::Subscription<diagnostic_msgs::msg::DiagnosticArray>::SharedPtr riptide_rviz::DiagnosticOverlay::diagSub
Referenced by onInitialize.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::DiagnosticOverlay::killSub
Referenced by updateNS.
rclcpp::Subscription<sensor_msgs::msg::Temperature>::SharedPtr riptide_rviz::DiagnosticOverlay::zedSub
Referenced by onInitialize.
rclcpp::Subscription<sensor_msgs::msg::Temperature>::SharedPtr riptide_rviz::DiagnosticOverlay::dfcSub
Referenced by onInitialize.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::DiagnosticOverlay::leakSub
Referenced by onInitialize.
rclcpp::Subscription<riptide_msgs2::msg::GyroStatus>::SharedPtr riptide_rviz::DiagnosticOverlay::gyroSub
Referenced by onInitialize.
rclcpp::Subscription<std_msgs::msg::Float32>::SharedPtr riptide_rviz::DiagnosticOverlay::pressureSub
Referenced by onInitialize.
rclcpp::Subscription<riptide_msgs2::msg::BatteryStatus>::SharedPtr riptide_rviz::DiagnosticOverlay::batterySub
Referenced by onInitialize.
rclcpp::Publisher<riptide_msgs2::msg::ElectricalCommand>::SharedPtr riptide_rviz::DiagnosticOverlay::batteryKillPub
Referenced by leakCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::pvtTextId
Referenced by checkTimeout, onInitialize.
int riptide_rviz::DiagnosticOverlay::diagLedConfigId
Referenced by checkTimeout, diagnosticCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::killLedConfigId
Referenced by checkTimeout, killCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::zedLedConfigId
Referenced by checkTimeout, onInitialize, zedCallback.
int riptide_rviz::DiagnosticOverlay::dfcLedConfigId
Referenced by checkTimeout, dfcCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::leakLedConfigId
Referenced by checkTimeout, leakCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::pressureLedConfigId
Referenced by checkTimeout, onInitialize, pressureCallback.
int riptide_rviz::DiagnosticOverlay::portBatterySocTextId
Referenced by batteryCallback, checkTimeout, onInitialize.
int riptide_rviz::DiagnosticOverlay::stbdBatterySocTextId
Referenced by batteryCallback, checkTimeout, onInitialize.
QStringList riptide_rviz::DiagnosticOverlay::fontFamilies
Referenced by DiagnosticOverlay, updateFont.
std::string riptide_rviz::DiagnosticOverlay::fontName
Referenced by onInitialize, updateFont.
double riptide_rviz::DiagnosticOverlay::tempMin
double riptide_rviz::DiagnosticOverlay::tempMax
rviz_common::properties::EnumProperty* riptide_rviz::DiagnosticOverlay::fontProperty
Referenced by DiagnosticOverlay, updateFont.
rviz_common::properties::StringProperty* riptide_rviz::DiagnosticOverlay::robotNsProperty
Referenced by DiagnosticOverlay, onInitialize, updateNS, ~DiagnosticOverlay.
rviz_common::properties::FloatProperty* riptide_rviz::DiagnosticOverlay::timeoutProperty
Referenced by checkTimeout, DiagnosticOverlay, ~DiagnosticOverlay.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::diagLedConfig
Referenced by checkTimeout, diagnosticCallback, onInitialize.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::killLedConfig
Referenced by checkTimeout, killCallback, onInitialize.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::zedLedConfig
Referenced by checkTimeout, onInitialize, zedCallback.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::dfcLedConfig
Referenced by checkTimeout, dfcCallback, onInitialize.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::leakLedConfig
Referenced by checkTimeout, leakCallback, onInitialize.
PaintedCircleConfig riptide_rviz::DiagnosticOverlay::pressureLedConfig
Referenced by checkTimeout, onInitialize, pressureCallback.
PaintedTextConfig riptide_rviz::DiagnosticOverlay::pvtConfig
Referenced by checkTimeout, onInitialize, pressureCallback.
PaintedTextConfig riptide_rviz::DiagnosticOverlay::stbdBatterySocConfig
Referenced by batteryCallback, checkTimeout, onInitialize.
PaintedTextConfig riptide_rviz::DiagnosticOverlay::portBatterySocConfig
Referenced by batteryCallback, checkTimeout, onInitialize.
PaintedArcConfig riptide_rviz::DiagnosticOverlay::tempGaugeArc
Referenced by onInitialize.
int riptide_rviz::DiagnosticOverlay::tempGaugeArcId
Referenced by onInitialize.
PaintedArcConfig riptide_rviz::DiagnosticOverlay::tempGaugeIndicator
Referenced by checkTimeout, gyroCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::tempGaugeIndicatorId
Referenced by checkTimeout, gyroCallback, onInitialize.
PaintedTextConfig riptide_rviz::DiagnosticOverlay::tempTextConfig
Referenced by checkTimeout, gyroCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::tempTextId
Referenced by checkTimeout, gyroCallback, onInitialize.
PaintedArcConfig riptide_rviz::DiagnosticOverlay::cpuTempGaugeArc
Referenced by onInitialize.
int riptide_rviz::DiagnosticOverlay::cpuTempGaugeArcId
Referenced by onInitialize.
PaintedArcConfig riptide_rviz::DiagnosticOverlay::cpuTempGaugeIndicator
Referenced by checkTimeout, diagnosticCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::cpuTempGaugeIndicatorId
Referenced by checkTimeout, diagnosticCallback, onInitialize.
PaintedTextConfig riptide_rviz::DiagnosticOverlay::cpuTempTextConfig
Referenced by checkTimeout, diagnosticCallback, onInitialize.
int riptide_rviz::DiagnosticOverlay::cpuTempTextId
Referenced by checkTimeout, diagnosticCallback, onInitialize.
riptide_rviz::DiagnosticOverlay::DiagnosticOverlay()
References fontFamilies, fontProperty, robotNsProperty, timeoutProperty, updateFont, updateNS.
riptide_rviz::DiagnosticOverlay::~DiagnosticOverlay()
References robotNsProperty, timeoutProperty.
void riptide_rviz::DiagnosticOverlay::onInitialize() override
References riptide_rviz::OverlayDisplay::addArc, riptide_rviz::OverlayDisplay::addCircle, riptide_rviz::OverlayDisplay::addText, batteryCallback, batteryKillPub, batterySub, checkTimeout, checkTimer, cpuTempGaugeArc, cpuTempGaugeArcId, cpuTempGaugeIndicator, cpuTempGaugeIndicatorId, cpuTempTextConfig, cpuTempTextId, dfcCallback, dfcLedConfig, dfcLedConfigId, dfcSub, diagLedConfig, diagLedConfigId, diagnosticCallback, diagSub, fontName, gyroCallback, gyroSub, killLedConfig, killLedConfigId, lastCpuTemp, lastDfc, lastDiag, lastGyro, lastKill, lastLeak, lastPressure, lastZed, leakCallback, leakLedConfig, leakLedConfigId, leakSub, riptide_rviz::OverlayDisplay::onInitialize, portBatterySocConfig, portBatterySocTextId, portlastBattery, pressureCallback, pressureLedConfig, pressureLedConfigId, pressureSub, pvtConfig, pvtTextId, robotNsProperty, stbdBatterySocConfig, stbdBatterySocTextId, stbdlastBattery, tempGaugeArc, tempGaugeArcId, tempGaugeIndicator, tempGaugeIndicatorId, tempTextConfig, tempTextId, zedCallback, zedLedConfig, zedLedConfigId, zedSub.
void riptide_rviz::DiagnosticOverlay::onEnable() override
References riptide_rviz::OverlayDisplay::onEnable.
void riptide_rviz::DiagnosticOverlay::onDisable() override
References riptide_rviz::OverlayDisplay::onDisable.
void riptide_rviz::DiagnosticOverlay::update(float wall_dt, float ros_dt) override
References riptide_rviz::OverlayDisplay::update.
void riptide_rviz::DiagnosticOverlay::reset() override
References riptide_rviz::OverlayDisplay::reset.
void riptide_rviz::DiagnosticOverlay::diagnosticCallback(const diagnostic_msgs::msg::DiagnosticArray &msg)
References cpuTempGaugeIndicator, cpuTempGaugeIndicatorId, cpuTempTextConfig, cpuTempTextId, cpuTempTimedOut, diagLedConfig, diagLedConfigId, diagsTimedOut, lastCpuTemp, lastDiag, riptide_rviz::OverlayDisplay::updateArc, riptide_rviz::OverlayDisplay::updateCircle, riptide_rviz::OverlayDisplay::updateText.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::killCallback(const std_msgs::msg::Bool &msg)
References killLedConfig, killLedConfigId, killTimedOut, lastKill, riptide_rviz::OverlayDisplay::updateCircle.
Referenced by updateNS.
void riptide_rviz::DiagnosticOverlay::zedCallback(const sensor_msgs::msg::Temperature &msg)
References lastZed, riptide_rviz::OverlayDisplay::updateCircle, zedLedConfig, zedLedConfigId, zedTimedOut.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::dfcCallback(const sensor_msgs::msg::Temperature &msg)
References dfcLedConfig, dfcLedConfigId, dfcTimedOut, lastDfc, riptide_rviz::OverlayDisplay::updateCircle.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::leakCallback(const std_msgs::msg::Bool &msg)
References batteryKillPub, lastLeak, leakLedConfig, leakLedConfigId, leakTimedOut, redFlash, startedLeaking, riptide_rviz::OverlayDisplay::updateCircle.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::gyroCallback(const riptide_msgs2::msg::GyroStatus &msg)
References gyroTimedOut, lastGyro, tempGaugeIndicator, tempGaugeIndicatorId, tempTextConfig, tempTextId, riptide_rviz::OverlayDisplay::updateArc, riptide_rviz::OverlayDisplay::updateText.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::pressureCallback(const std_msgs::msg::Float32 &msg)
References lastPressure, pressureLedConfig, pressureLedConfigId, pressureTimedOut, pvtConfig, redFlash, riptide_rviz::OverlayDisplay::updateCircle.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::batteryCallback(const riptide_msgs2::msg::BatteryStatus &msg)
References portBatterySocConfig, portBatterySocTextId, portBatteryTimedOut, portlastBattery, stbdBatterySocConfig, stbdBatterySocTextId, stbdBatteryTimedOut, stbdlastBattery, riptide_rviz::OverlayDisplay::updateText.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::checkTimeout()
References cpuTempGaugeIndicator, cpuTempGaugeIndicatorId, cpuTempTextConfig, cpuTempTextId, cpuTempTimedOut, dfcLedConfig, dfcLedConfigId, dfcTimedOut, diagLedConfig, diagLedConfigId, diagsTimedOut, gyroTimedOut, killLedConfig, killLedConfigId, killTimedOut, lastCpuTemp, lastDfc, lastDiag, lastGyro, lastKill, lastLeak, lastPressure, lastZed, leakLedConfig, leakLedConfigId, leakTimedOut, portBatterySocConfig, portBatterySocTextId, portBatteryTimedOut, portlastBattery, pressureLedConfig, pressureLedConfigId, pressureTimedOut, pvtConfig, pvtTextId, stbdBatterySocConfig, stbdBatterySocTextId, stbdBatteryTimedOut, stbdlastBattery, tempGaugeIndicator, tempGaugeIndicatorId, tempTextConfig, tempTextId, timeoutProperty, riptide_rviz::OverlayDisplay::updateArc, riptide_rviz::OverlayDisplay::updateCircle, riptide_rviz::OverlayDisplay::updateText, zedLedConfig, zedLedConfigId, zedTimedOut.
Referenced by onInitialize.
void riptide_rviz::DiagnosticOverlay::updateFont()
References fontFamilies, fontName, fontProperty, riptide_rviz::OverlayDisplay::require_update_texture_.
Referenced by DiagnosticOverlay.
void riptide_rviz::DiagnosticOverlay::updateNS()
References killCallback, killSub, robotNsProperty.
Referenced by DiagnosticOverlay.