riptide_rviz::BaggingPanel
Ui_BaggingPanel* riptide_rviz::BaggingPanel::uiPanel
Referenced by autonomyTriggerCallback, BaggingPanel, clearScrollArea, fileListRefresh, handleBaggingPanelFile, handleBaggingPanelHost, hostListRefresh, onInitialize, setGlobalBagState, waitForWhois, ~BaggingPanel.
QWidget* riptide_rviz::BaggingPanel::mainParent
Referenced by BaggingPanel.
QWidget* riptide_rviz::BaggingPanel::scrollAreaLayout
Referenced by clearScrollArea.
QVBoxLayout* riptide_rviz::BaggingPanel::vbox
Referenced by baggingStateCallback, clearScrollArea, handleBaggingPanelFile, waitForWhois.
std::vector<BagItem *> riptide_rviz::BaggingPanel::bagList
Referenced by baggingStateCallback, clearScrollArea, handleBaggingPanelFile, setGlobalBagState, waitForWhois.
rclcpp::Subscription<launch_msgs::msg::ListPids>::SharedPtr riptide_rviz::BaggingPanel::baggingStateSub
Referenced by handleBaggingPanelHost.
rclcpp::Subscription<std_msgs::msg::Bool>::SharedPtr riptide_rviz::BaggingPanel::bagTriggerSub
Referenced by handleBaggingPanelHost.
rclcpp::Client<launch_msgs::srv::WhoIs>::SharedPtr riptide_rviz::BaggingPanel::bagWhoIsClient
Referenced by baggingStateCallback, handleBaggingPanelHost, waitForWhois.
std::shared_future<std::shared_ptr<launch_msgs::srv::WhoIs_Response> > riptide_rviz::BaggingPanel::whoisFuture
Referenced by baggingStateCallback, waitForWhois.
int64_t riptide_rviz::BaggingPanel::whoisReqId
Referenced by baggingStateCallback, waitForWhois.
unsigned int riptide_rviz::BaggingPanel::timerTick
Referenced by baggingStateCallback, waitForWhois.
std::vector<int> riptide_rviz::BaggingPanel::nonLocals
Referenced by baggingStateCallback, waitForWhois.
bool riptide_rviz::BaggingPanel::runningAll
Referenced by fileListRefresh, startBagging.
std_msgs::msg::Bool riptide_rviz::BaggingPanel::priorBagState
Referenced by autonomyTriggerCallback, fileListRefresh, startBagging.
riptide_rviz::BaggingPanel::BaggingPanel(QWidget *parent=0)
References mainParent, uiPanel.
riptide_rviz::BaggingPanel::~BaggingPanel()
References uiPanel.
void riptide_rviz::BaggingPanel::load(const rviz_common::Config &config) override
void riptide_rviz::BaggingPanel::save(rviz_common::Config config) const override
void riptide_rviz::BaggingPanel::onInitialize() override
References clearScrollArea, fileListRefresh, handleBaggingPanelFile, handleBaggingPanelHost, hostListRefresh, uiPanel.
void riptide_rviz::BaggingPanel::clearScrollArea()
References bagList, scrollAreaLayout, uiPanel, vbox.
Referenced by handleBaggingPanelFile, onInitialize.
void riptide_rviz::BaggingPanel::baggingConfigure()
void riptide_rviz::BaggingPanel::hostListRefresh()
References uiPanel.
Referenced by onInitialize.
void riptide_rviz::BaggingPanel::fileListRefresh()
References priorBagState, runningAll, RVIZ_PKG, uiPanel.
Referenced by handleBaggingPanelHost, onInitialize.
void riptide_rviz::BaggingPanel::handleBaggingPanelHost(const QString &text)
References autonomyTriggerCallback, baggingStateCallback, baggingStateSub, bagTriggerSub, bagWhoIsClient, fileListRefresh, uiPanel.
Referenced by onInitialize.
void riptide_rviz::BaggingPanel::handleBaggingPanelFile(const QString &text)
References bagList, clearScrollArea, riptide_rviz::getRecipeXMLErrorMessage, RVIZ_PKG, riptide_rviz::SUCCESS, uiPanel, vbox.
Referenced by onInitialize.
void riptide_rviz::BaggingPanel::startBagging()
References priorBagState, runningAll, setGlobalBagState.
void riptide_rviz::BaggingPanel::setGlobalBagState(bool run)
References bagList, uiPanel.
Referenced by autonomyTriggerCallback, startBagging.
bool riptide_rviz::BaggingPanel::event(QEvent *event)
References event.
Referenced by event.
void riptide_rviz::BaggingPanel::waitForWhois()
References bagList, bagWhoIsClient, nonLocals, timerTick, uiPanel, vbox, waitForWhois, whoisFuture, whoisReqId.
Referenced by baggingStateCallback, waitForWhois.
void riptide_rviz::BaggingPanel::baggingStateCallback(const launch_msgs::msg::ListPids &msg)
References bagList, bagWhoIsClient, nonLocals, timerTick, vbox, waitForWhois, whoisFuture, whoisReqId.
Referenced by handleBaggingPanelHost.
void riptide_rviz::BaggingPanel::autonomyTriggerCallback(const std_msgs::msg::Bool &msg)
References priorBagState, setGlobalBagState, uiPanel.
Referenced by handleBaggingPanelHost.