riptide_rviz::FeedforwardPanel
std::string riptide_rviz::FeedforwardPanel::config_path
YAML::Node riptide_rviz::FeedforwardPanel::config
Referenced by load, save, ZFunction.
bool riptide_rviz::FeedforwardPanel::loaded
Referenced by load.
bool riptide_rviz::FeedforwardPanel::publishing
Referenced by togglePublish.
int riptide_rviz::FeedforwardPanel::counter
Ui_FeedforwardPanel* riptide_rviz::FeedforwardPanel::ui
Referenced by FeedforwardPanel, onInitialize, PFunction, RFunction, togglePublish, XFunction, YAWFunction, YFunction, ZFunction, ~FeedforwardPanel.
QString riptide_rviz::FeedforwardPanel::robotNs
Referenced by load, save.
rclcpp::TimerBase::SharedPtr riptide_rviz::FeedforwardPanel::pubTimer
Referenced by load, togglePublish.
rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr riptide_rviz::FeedforwardPanel::ffForcePub
Referenced by load, timerCb.
geometry_msgs::msg::Twist riptide_rviz::FeedforwardPanel::msgToPublish
Referenced by PFunction, RFunction, timerCb, XFunction, YAWFunction, YFunction, ZFunction.
riptide_rviz::FeedforwardPanel::FeedforwardPanel(QWidget *parent=0)
References ui.
riptide_rviz::FeedforwardPanel::~FeedforwardPanel()
References ui.
void riptide_rviz::FeedforwardPanel::load(const rviz_common::Config &config) override
References config, ffForcePub, loaded, pubTimer, robotNs, timerCb.
void riptide_rviz::FeedforwardPanel::save(rviz_common::Config config) const override
References config, robotNs.
void riptide_rviz::FeedforwardPanel::onInitialize() override
References PFunction, RFunction, togglePublish, ui, XFunction, YAWFunction, YFunction, ZFunction.
void riptide_rviz::FeedforwardPanel::XFunction(double value)
References msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::YFunction(double value)
References msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::ZFunction(double value)
References config, msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::RFunction(double value)
References msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::PFunction(double value)
References msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::YAWFunction(double value)
References msgToPublish, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::togglePublish()
References publishing, pubTimer, ui.
Referenced by onInitialize.
void riptide_rviz::FeedforwardPanel::timerCb()
References ffForcePub, msgToPublish.
Referenced by load.