riptide_rviz::ElectricalPanel
using riptide_rviz::ElectricalPanel::MagCal = riptide_msgs2::action::MagCal
using riptide_rviz::ElectricalPanel::MagSendGoalOptions = rclcpp_action::Client<MagCal>::SendGoalOptions
using riptide_rviz::ElectricalPanel::MagGoalHandle = rclcpp_action::Client<MagCal>::GoalHandle
using riptide_rviz::ElectricalPanel::TareGyro = riptide_msgs2::action::TareGyro
using riptide_rviz::ElectricalPanel::TareGyroSendGoalOptions = rclcpp_action::Client<TareGyro>::SendGoalOptions
using riptide_rviz::ElectricalPanel::TareGyroGoalHandle = rclcpp_action::Client<TareGyro>::GoalHandle
using riptide_rviz::ElectricalPanel::Depressurize = riptide_msgs2::action::Depressurize
using riptide_rviz::ElectricalPanel::DepressurizeSendGoalOptions = rclcpp_action::Client<Depressurize>::SendGoalOptions
using riptide_rviz::ElectricalPanel::DepressurizeGoalHandle = rclcpp_action::Client<Depressurize>::GoalHandle
using riptide_rviz::ElectricalPanel::ImuConfig = riptide_msgs2::srv::QueryImuSerial
bool riptide_rviz::ElectricalPanel::loaded
Referenced by ElectricalPanel, load, sendDepressurizationCommand, sendElectricalCommand, sendMagCal, sendTareGyro.
Ui_ElectricalPanel* riptide_rviz::ElectricalPanel::ui
Referenced by appendIvcConsole, depressurizeFeedbackCb, depressurizeResultCb, ElectricalPanel, magCalFeedbackCb, magCalResultCb, onInitialize, readIMU, sendDepressurizationCommand, sendElectricalCommand, sendIvcMsg, sendMagCal, sendTareGyro, setStatus, tareGyroResultCb, waitForConfig, writeIMU, ~ElectricalPanel.
QString riptide_rviz::ElectricalPanel::robotNs
Referenced by load, save.
bool riptide_rviz::ElectricalPanel::imuCalInProgress
Referenced by magCalResultCb, sendDepressurizationCommand, sendMagCal, sendTareGyro.
bool riptide_rviz::ElectricalPanel::gyroTareInProgress
Referenced by sendMagCal, sendTareGyro, tareGyroGoalResponseCb, tareGyroResultCb.
bool riptide_rviz::ElectricalPanel::depressurizationInProgress
Referenced by depressurizeResultCb, sendDepressurizationCommand, sendMagCal, sendTareGyro.
double riptide_rviz::ElectricalPanel::maxVar
Referenced by magCalFeedbackCb, sendMagCal.
double riptide_rviz::ElectricalPanel::netDepressurization
Referenced by depressurizeFeedbackCb, sendDepressurizationCommand.
bool riptide_rviz::ElectricalPanel::imuHsiEnable
bool riptide_rviz::ElectricalPanel::imuHsiOutput
int riptide_rviz::ElectricalPanel::imuConvergenceRate
rclcpp::Publisher<riptide_msgs2::msg::ElectricalCommand>::SharedPtr riptide_rviz::ElectricalPanel::elecPub
Referenced by load, sendElectricalCommand.
rclcpp::Publisher<std_msgs::msg::UInt8>::SharedPtr riptide_rviz::ElectricalPanel::ivcTxPub
Referenced by load, sendIvcMsg.
rclcpp::Subscription<std_msgs::msg::UInt8>::SharedPtr riptide_rviz::ElectricalPanel::ivcTxSub
Referenced by load.
rclcpp::Subscription<std_msgs::msg::UInt8>::SharedPtr riptide_rviz::ElectricalPanel::ivcRxSub
Referenced by load.
rclcpp::Subscription<riptide_msgs2::msg::UInt8Stamped>::SharedPtr riptide_rviz::ElectricalPanel::ivcSuccessSub
Referenced by load.
rclcpp_action::Client<MagCal>::SharedPtr riptide_rviz::ElectricalPanel::imuCalClient
Referenced by load, sendMagCal.
rclcpp_action::Client<TareGyro>::SharedPtr riptide_rviz::ElectricalPanel::tareGyroClient
Referenced by load, sendTareGyro.
rclcpp_action::Client<Depressurize>::SharedPtr riptide_rviz::ElectricalPanel::depressurizeClient
Referenced by load, sendDepressurizationCommand.
rclcpp::Client<ImuConfig>::SharedPtr riptide_rviz::ElectricalPanel::imuConfigClient
Referenced by load, sendIMUConfigRequest, waitForConfig.
std::shared_future<std::shared_ptr<riptide_msgs2::srv::QueryImuSerial_Response> > riptide_rviz::ElectricalPanel::imuConfigFuture
Referenced by sendIMUConfigRequest, waitForConfig.
int riptide_rviz::ElectricalPanel::timerTick
Referenced by sendIMUConfigRequest, waitForConfig.
int riptide_rviz::ElectricalPanel::imuConfigFutureId
Referenced by sendIMUConfigRequest, waitForConfig.
riptide_rviz::ElectricalPanel::ElectricalPanel(QWidget *parent=0)
References loaded, setStatus, ui.
riptide_rviz::ElectricalPanel::~ElectricalPanel()
References ui.
void riptide_rviz::ElectricalPanel::load(const rviz_common::Config &config) override
References riptide_rviz::CONFIG_SERVICE_NAME, riptide_rviz::DEPRESSURIZE_ACTION_NAME, depressurizeClient, elecPub, imuCalClient, imuConfigClient, ivcRxCb, ivcRxSub, ivcSuccessSub, ivcTxCb, ivcTxPub, ivcTxSub, ivcTxSuccessCb, loaded, riptide_rviz::MAG_CAL_ACTION_NAME, robotNs, riptide_rviz::TARE_GYRO_ACTION_NAME, tareGyroClient.
void riptide_rviz::ElectricalPanel::save(rviz_common::Config config) const override
References robotNs.
void riptide_rviz::ElectricalPanel::onInitialize() override
References readIMU, saveImuSettings, sendDepressurizationCommand, sendElectricalCommand, sendIvcMsg, sendMagCal, sendTareGyro, setStatus, ui, writeIMU.
void riptide_rviz::ElectricalPanel::sendElectricalCommand()
References elecPub, loaded, setStatus, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::sendDepressurizationCommand()
References depressurizationInProgress, depressurizeClient, depressurizeFeedbackCb, depressurizeGoalResponseCb, depressurizeResultCb, imuCalInProgress, loaded, netDepressurization, setStatus, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::sendMagCal()
References depressurizationInProgress, gyroTareInProgress, imuCalClient, imuCalInProgress, loaded, magCalFeedbackCb, magCalGoalResponseCb, magCalResultCb, maxVar, setStatus, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::sendTareGyro()
References depressurizationInProgress, gyroTareInProgress, imuCalInProgress, loaded, setStatus, tareGyroClient, tareGyroGoalResponseCb, tareGyroResultCb, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::sendIvcMsg()
References ivcTxPub, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::writeIMU()
References sendIMUConfigRequest, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::readIMU()
References sendIMUConfigRequest, ui.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::saveImuSettings()
References sendIMUConfigRequest.
Referenced by onInitialize.
void riptide_rviz::ElectricalPanel::setStatus(const QString &status, bool error)
References ui.
Referenced by depressurizeFeedbackCb, depressurizeResultCb, ElectricalPanel, magCalGoalResponseCb, magCalResultCb, onInitialize, sendDepressurizationCommand, sendElectricalCommand, sendIMUConfigRequest, sendMagCal, sendTareGyro, tareGyroGoalResponseCb, tareGyroResultCb, waitForConfig.
void riptide_rviz::ElectricalPanel::appendIvcConsole(const QString &prefix, const uint8_t &msg)
References ui.
Referenced by ivcRxCb, ivcTxCb, ivcTxSuccessCb.
void riptide_rviz::ElectricalPanel::magCalGoalResponseCb(const MagGoalHandle::SharedPtr &goal_handle)
References setStatus.
Referenced by sendMagCal.
void riptide_rviz::ElectricalPanel::magCalFeedbackCb(MagGoalHandle::SharedPtr, const std::shared_ptr< const MagCal::Feedback > feedback)
References maxVar, ui.
Referenced by sendMagCal.
void riptide_rviz::ElectricalPanel::magCalResultCb(const MagGoalHandle::WrappedResult &result)
References imuCalInProgress, setStatus, ui.
Referenced by sendMagCal.
void riptide_rviz::ElectricalPanel::ivcTxCb(const std_msgs::msg::UInt8::SharedPtr msg)
References appendIvcConsole.
Referenced by load.
void riptide_rviz::ElectricalPanel::ivcRxCb(const std_msgs::msg::UInt8::SharedPtr msg)
References appendIvcConsole.
Referenced by load.
void riptide_rviz::ElectricalPanel::ivcTxSuccessCb(const riptide_msgs2::msg::UInt8Stamped::SharedPtr msg)
References appendIvcConsole.
Referenced by load.
void riptide_rviz::ElectricalPanel::tareGyroGoalResponseCb(const TareGyroGoalHandle::SharedPtr &goal_handle)
References gyroTareInProgress, setStatus.
Referenced by sendTareGyro.
void riptide_rviz::ElectricalPanel::tareGyroResultCb(const TareGyroGoalHandle::WrappedResult &result)
References gyroTareInProgress, setStatus, ui.
Referenced by sendTareGyro.
void riptide_rviz::ElectricalPanel::depressurizeGoalResponseCb(const DepressurizeGoalHandle::SharedPtr &goal_handle)
Referenced by sendDepressurizationCommand.
void riptide_rviz::ElectricalPanel::depressurizeFeedbackCb(DepressurizeGoalHandle::SharedPtr, const std::shared_ptr< const Depressurize::Feedback > feedback)
References netDepressurization, setStatus, ui.
Referenced by sendDepressurizationCommand.
void riptide_rviz::ElectricalPanel::depressurizeResultCb(const DepressurizeGoalHandle::WrappedResult &result)
References depressurizationInProgress, setStatus, ui.
Referenced by sendDepressurizationCommand.
Qt::CheckState riptide_rviz::ElectricalPanel::processCheckState(bool state)
void riptide_rviz::ElectricalPanel::resultCb(const MagGoalHandle::WrappedResult &result)
void riptide_rviz::ElectricalPanel::sendIMUConfigRequest(const std::string &request, bool extResponseTime=false)
References imuConfigClient, imuConfigFuture, imuConfigFutureId, setStatus, timerTick, waitForConfig.
Referenced by readIMU, saveImuSettings, writeIMU.
void riptide_rviz::ElectricalPanel::waitForConfig(bool extResponseTime=false)
References imuConfigClient, imuConfigFuture, imuConfigFutureId, setStatus, timerTick, ui, waitForConfig.
Referenced by sendIMUConfigRequest, waitForConfig.