riptide_rviz::MappingPanel
using riptide_rviz::MappingPanel::ModelFrame = chameleon_tf_msgs::action::ModelFrame
using riptide_rviz::MappingPanel::SendGoalOptions = rclcpp_action::Client<ModelFrame>::SendGoalOptions
using riptide_rviz::MappingPanel::CalibGoalHandle = rclcpp_action::Client<ModelFrame>::GoalHandle
using riptide_rviz::MappingPanel::MappingTarget = riptide_msgs2::srv::MappingTarget
using riptide_rviz::MappingPanel::Trigger = std_srvs::srv::Trigger
Ui_MappingPanel* riptide_rviz::MappingPanel::ui
Referenced by calibMapFrame, dfcRecordStart, dfcRecordStop, feedbackCb, load, mappingObjectCb, MappingPanel, mappingStatusCb, onInitialize, resultCb, save, setMappingTarget, setStatus, updateDfcRecordingIndicator, updateFfcRecordingIndicator, zedSvoStart, zedSvoStop, ~MappingPanel.
std::string riptide_rviz::MappingPanel::robotNs
Referenced by load, save.
bool riptide_rviz::MappingPanel::calibrationInProgress
Referenced by calibMapFrame, onInitialize, resultCb.
bool riptide_rviz::MappingPanel::loaded
Referenced by calibMapFrame, load, MappingPanel.
rclcpp_action::Client<chameleon_tf_msgs::action::ModelFrame>::SharedPtr riptide_rviz::MappingPanel::calibClient
Referenced by calibMapFrame, load.
rclcpp::Subscription<riptide_msgs2::msg::MappingTargetInfo>::SharedPtr riptide_rviz::MappingPanel::mappingTargetInfoSub
Referenced by load.
rclcpp::Subscription<geometry_msgs::msg::PoseWithCovarianceStamped>::SharedPtr riptide_rviz::MappingPanel::mappingObjectSub
Referenced by load.
GuiSrvClient<MappingTarget>::SharedPtr riptide_rviz::MappingPanel::mappingTargetClient
Referenced by load, setMappingTarget.
GuiSrvClient<Trigger>::SharedPtr riptide_rviz::MappingPanel::captureImageClient
Referenced by captureImage, load.
riptide_rviz::MappingPanel::MappingPanel(QWidget *parent=0)
References loaded, ui.
riptide_rviz::MappingPanel::~MappingPanel()
References ui.
void riptide_rviz::MappingPanel::load(const rviz_common::Config &config) override
References riptide_rviz::CALIB_ACTION_NAME, calibClient, captureImageClient, riptide_rviz::getFromConfig, loaded, mappingObjectCb, mappingObjectSub, mappingStatusCb, mappingTargetClient, mappingTargetInfoSub, mappingTargetResultCb, robotNs, serviceResponseCb, setStatus, ui.
void riptide_rviz::MappingPanel::save(rviz_common::Config config) const override
References robotNs, ui.
void riptide_rviz::MappingPanel::onInitialize() override
References calibMapFrame, calibrationInProgress, captureImage, dfcRecordStart, dfcRecordStop, setMappingTarget, ui, zedSvoStart, zedSvoStop.
void riptide_rviz::MappingPanel::calibMapFrame()
References calibClient, calibrationInProgress, feedbackCb, goalResponseCb, loaded, resultCb, setStatus, ui.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::setMappingTarget()
References mappingTargetClient, ui.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::zedSvoStart()
References setStatus, ui, updateFfcRecordingIndicator.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::zedSvoStop()
References ui, updateFfcRecordingIndicator.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::dfcRecordStart()
References setStatus, ui, updateDfcRecordingIndicator.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::dfcRecordStop()
References ui, updateDfcRecordingIndicator.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::captureImage()
References captureImageClient.
Referenced by onInitialize.
void riptide_rviz::MappingPanel::setStatus(const QString &text, const QString &color)
References ui.
Referenced by calibMapFrame, dfcRecordStart, feedbackCb, goalResponseCb, load, mappingTargetResultCb, resultCb, serviceResponseCb, zedSvoStart.
void riptide_rviz::MappingPanel::updateFfcRecordingIndicator(bool recording)
References ui.
Referenced by zedSvoStart, zedSvoStop.
void riptide_rviz::MappingPanel::updateDfcRecordingIndicator(bool recording)
References ui.
Referenced by dfcRecordStart, dfcRecordStop.
void riptide_rviz::MappingPanel::serviceResponseCb(const std::string &srvName, typename rclcpp::Client< T >::SharedResponse response)
References setStatus.
Referenced by load.
void riptide_rviz::MappingPanel::goalResponseCb(const CalibGoalHandle::SharedPtr &goal_handle)
References setStatus.
Referenced by calibMapFrame.
void riptide_rviz::MappingPanel::feedbackCb(CalibGoalHandle::SharedPtr, const std::shared_ptr< const ModelFrame::Feedback > feedback)
References setStatus, ui.
Referenced by calibMapFrame.
void riptide_rviz::MappingPanel::resultCb(const CalibGoalHandle::WrappedResult &result)
References calibrationInProgress, setStatus, ui.
Referenced by calibMapFrame.
void riptide_rviz::MappingPanel::mappingStatusCb(const riptide_msgs2::msg::MappingTargetInfo::SharedPtr msg)
References ui.
Referenced by load.
void riptide_rviz::MappingPanel::mappingObjectCb(const geometry_msgs::msg::PoseWithCovarianceStamped::SharedPtr msg)
References ui.
Referenced by load.
void riptide_rviz::MappingPanel::mappingTargetResultCb(const std::string &srvName, rclcpp::Client< MappingTarget >::SharedResponse response)
References setStatus.
Referenced by load.