name: Build & Publish Docs
on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install and Build Sphinx Site
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip3 install -yr requirements.txt

          make build
